<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'A problem occurred during the Data and Access Permission save action' => 'Es ist ein Problem beim Speichern der Daten- und Zugriffsberechtigungen aufgetreten',
  'A problem occurred during the configuration save action' => 'Es is ein Problem Speichern der Konfiguration aufgetreten',
  'A problem occurred during the cron jobs configuration save action' => 'Es ist ein Problem beim Speichern der Cron-Job Aktionen aufgetreten',
  'Cron Jobs Configuration Saved' => 'Cron Jobs Konfiguration gespeichert',
  'You cannot change the Access Permissions of the Root User' => 'Sie können nicht die Zugriffsrechte der Benutzers \'Root\' ändern',
  'You cannot delete a user/group with a higher level then yours.' => 'Sie können keine Benutzer/Gruppen löschen die eine höheren Level als Sie selbst haben',
  'You don\'t have the permission to delete any user/group' => 'Sie haben keine Zugriffsrechte um einen Benutzer oder eine Gruppe zu löschen.',
  'all' => 'Alle',
  'click here to return to the admin page' => 'Hier klicken um zur Administrationseite zurückzukehren',
  'click here update userGroups' => 'Hier klicken um userGroups zu aktualisieren',
  'if you omit the username the user will be able to chose one upon activation of the account' => 'Wenn Sie keinen Benutzernamen angeben kann der Benutzer beim Aktivieren des Accounts einen auswählen.',
  'it was not possible to get the value of permissionControl inside your controller. Check your Controller.' => 'Es war nicht möglich das Attribute von permissionControl aus Ihrem Controller zu lesen. Bitte überprüfen Sie Ihren Controller.',
  'update to version {version}' => 'Auf version {version} updaten',
  'About the author' => 'Über den Autor',
  'Ban Period' => 'Bannperiode',
  'Ban Reason' => 'Banngrund',
  'Controller' => 'Controller',
  'Cron Jobs' => 'Cron Jobs',
  'Cron Jobs successfully removed' => 'Cron Jobs erfolgreich entfernt',
  'Data and Access Permission of <i>{displayname} group</i> changed' => 'Daten und Zugriffsrechte für <i>Gruppe {displayname}</i> geändert',
  'Data and Access Permission of <i>{displayname} user</i> changed' => 'Daten und Zugriffsrechte für <i>User {displayname}</i> geändert',
  'Description' => 'Beschreibung',
  'Do you really want to approve {who} registration?' => 'Wollen Sie die Registration von Benutzer {who} wirklich bestätigen?',
  'Do you really want to ban {who}?' => 'Wollen Sie den Benutzer {who} wirklich bannen?',
  'Do you really want to delete the group {group}?' => 'Wollen Sie die Gruppe {group} wirklich löschen?',
  'Do you really want to delete the user {user}?' => 'Wollen Sie dien Benutzer {user} wirklich löschen?',
  'Do you really want to remove those CronJobs?' => 'Wollen Sieden Cron Job wirklich löschen?',
  'Documentation' => 'Dokumentation',
  'Element' => 'Element',
  'Email Customization' => 'Anpassen der Email Nachricht',
  'First Steps' => 'Erste Schritte',
  'Forever' => 'Für immer',
  'Group Home: {home}' => 'Startseite der Gruppe: {home}',
  'Group {groupname}: Data and Access Permissions' => 'Gruppe {groupname}: Daten zund Zugriffskontrolle',
  'Impossible to delete the requested user/group. An Error Occurred' => 'Es is nicht möglich die genwünschte(n) Benutzer/Gruppe zu löschen. Es ist ein Fehler aufgetreten.',
  'Invalid Request.' => 'Ungültige Anfrage',
  'Is this thing safe?' => 'Ist diese Sache sicher?',
  'Lapse' => 'Interval',
  'Last Execution' => 'Letzte Ausführung',
  'License' => 'Lizenz',
  'Localization' => 'Lokalisierung',
  'Main Configurations' => 'Hauptkonfiguration',
  'Module' => 'Modul',
  'New Configurations Saved' => 'Neue Konfiguration gespeichert',
  'New Group: Data and Access Permissions' => 'Neue Gruppe: Daten und Zugriffsrechte',
  'New User: Data and Access Permissions' => 'Neuer Benutzer: Daten und Zugriffsrechte',
  'New group Created.' => 'Neue Gruppe angelegt.',
  'New user Created.' => 'Neuen Benutzer angelegt.',
  'Options' => 'Optionen',
  'Permission' => 'Zugriffsrechte',
  'Permission granted from Group' => 'Zugriffrechte durch Gruppe',
  'Profile Extensions' => 'Profil Erweiterungen',
  'Remember if you delete a Group you\'ll delete all the users that belongs to it.' => 'Beachten Sie, wenn Sie eine Gruppe löschen werden alle Mitglieder der Gruppe ebenfalls gelöscht.',
  'Remove not installed CronJobs' => 'Lösche nicht installierte Cron Jobs',
  'Root Tools' => 'Root Werkzeuge',
  'Setting' => 'Einstellungen',
  'Setup the new accessControlFilter' => 'Neuen accessControlFilter einstellen',
  'Status' => 'Status',
  'The following problems occurred: {errors}' => 'Es sind folgende Probleme aufgetreten: {errors}',
  'The requested cron does not exist.' => 'Der gewünschte Cron Job existiert nicht.',
  'The requested rule does not exist.' => 'Die Gewünschte Regel existiert nicht.',
  'The requested user/group does not exist and cannot be deleted.' => 'Der/Die gewünschte Benutzer/Gruppe existiert nicht und kann nicht geösht werden.',
  'This group does not exist' => 'Diese Gruppe existiert micht',
  'User {username}: Data and Access Permissions' => 'Benutzer {username}: Daten und Zugriffsrechte',
  'Using the new Access Rules' => 'Neue Zugriffsregel benutzen',
  'Value' => 'Wert',
  'What\'s coming next?' => 'Was kommt als nächstes?',
  'What\'s new?' => 'Was ist neu?',
  'You are not allowed to change any configuration' => 'Sie haben keine Berecjtigung die Konfigutration zu ändern',
  'You are not allowed to change the cron jobs configuration' => 'Sie haben keine Berechtigung die Konfiguration der Cron Jobs zu ändern',
  'You are not allowed to remove cron jobs' => 'Sie haben keine Berechtigung um Cron Jobs zu löschen',
  'You cannot assign to a User a Group that has a Level equal or higher then the one you belong to' => 'Sie können keinen Benutzer einer Gruppe hinzufügen dessen Level gleich oder höher als ihr Eigener ist.',
  'You cannot ban a user with a level higher then yours.' => 'Sie können keinen Benutzer bannen dess Level höher ist als Ihr Eigener.',
  'You cannot change constant values' => 'Sie können keine konstanten Werte ändern',
  'You cannot change data or permissions of Root' => 'Sie können weder Daten noch Zugriffsrechte des Root-Benutzer bearbeiten',
  'You cannot change data or permissions of a user or a group with a level higher then yours' => 'Sie können keine Daten oder Zugriffsrechte von Benutzern oder Gruppen änderen, deren Level höher als Ihr Eigener ist',
  'You cannot create a new user or group' => 'Sie können keine(n) neue Gruppe/neuen Benutzer anlegen',
  'You cannot set a Group Level equal or higher then Root' => 'Sie können einen Gruppenlevel nicht gleich oder höher als der des Root-Benutzers',
  'You cannot set a Group Level equal or superior to your own' => 'Sie können einen Gruppenlevel nicht gleich oder höher als Ihren Eigenen setzen',
  'You cannot set this value to a level equal or higher then your own' => 'Sie können diesen Wert nicht auf einen Level setzten, der gleich oder höher als Ihr Eigener ist',
  'You didn\'t supply a valid id' => 'Sie haben keine gültige ID angegeben',
  'add group' => 'Gruppe hinzufügen',
  'add user' => 'Benutzer hinzufügen',
  'if you omit the password a random one will be generated' => 'Wenn sie kein Passwort vergeben wird ein Zufälliges generiert.',
  'invalid value' => 'Ungültiger Wert',
  '{class}.allowAutoLogin must be set true in order to use cookie-based authentication.' => '{class}.allowAutoLogin muss auf true gesetzt werden um ein Cookie-basierte Authentifizierung zu ermöglichen.',
  '{n} Day|{n} Days' => '{n} Tag|{n} Tage',
  '{n} Month|{n} Months' => '{n} Monat|{n} Monate',
  '{n} Week|{n} Weeks' => '{n} Woche|{n} Wochen',
  '{username}\'s account is banned untill {day}.' => 'Das Benutzerkonto von {username} wurde bis zum {day} gebannt',
  '{username}\'s account is now active.' => 'Das Benutzerkonto von {username} ist jetzt aktiv',
  '{what} deleted.' => '{what} gelöscht.',
);
