<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  0 => '',
  'allow everyone, even guests, to see user profiles' => 'erlaubt allen (auch Gästen) die Benutzerprofile zu sehen',
  'allow user registration' => 'erlaubt die Benuzterregistrierung',
  'if a user has on a controller admin permissions will have access to write and read pages. If he has write permissions will also have access to read pages' => 'Wenn ein Benutzer Admin-Rechte für einen Controller besitzt, so beinhaltet dies auch Schreib- und Leserechte., Schreibrechte zusätzlich umfassen immer die Leserechte',
  'if true crons must be executed from the server using a crontab' => 'Wenn der Wert \'true\' ist, müssen die Crons-Jobs vom Server mittels einer crontab ausgeführt werden',
  'if true users just have to provide user and email to reset their password.<br/>Otherwise they will have to answer their custom question' => 'Wenn der Wert \'true\' ist, dann müssen Benutzer Ihren Benutzernamen und ihre E-mail Adresse angeben um ein Passwort zurückzusetzen. Im anderen Fall müssen Sie ihre benutzerdefinierte Frage beantworten',
  'if true when a user creates an account a mail with an activation code will be sent to his email address' => 'se &egrave; settato su TRUE quando un utente crea un account una mail con un codice di attivazione gli sar&agrave; inviata al suo indirizzo email',
  'if true when a user creates an account a user with user admin rights will have to approve the registration.<br/>If both this setting and user_need_activation are true the user will need to activate is account first and then will need the approval' => 
  'Wenn der Wert \'true\' ist, dann muss eine Bnutzerregistrierung immer von einem Benutzer mit Administratorrechten bestätigt werden.<br/>Wenn diese Einstellung und "user_need_activation" \'true\' sind, dann muss der Benutzer erst seinen Benutzerkonto aktivieren und dann muss die Aktivierung bestätigt werden.',
  'logged user can see other users profiles' => 'Angemeldete Benutzer können andere Benutzerprofile sehen',
  'logged users can see the complete user list' => 'Angemeldetet Benutzer können die gesamte Benutzerliste sehen',
  'password strength:<br/>weak: password of at least 5 characters, any character allowed.<br/>
			medium: password of at least 5 characters, must contain at least 2 digits and 2 letters.<br/>
			strong: password of at least 5 characters, must contain at least 2 digits, 2 letters and a special character.' => 
			'Passwortstärke: <br/>schwach: Passwortlänge mindestens 5 Zeichen, alle Zeichen erlaubt.<br/>
			mittel: Passwortlänge mindestens 5 Zeichen, muss aber mindestens 2 Ziffern und 2 Buchstaben enthalten<br/>
			stark: Passwortlänge mindestens 5 Zeichen, muss aber mindestens 2 Ziffern, 2 Buchstaben enthalten und ein spezielles Zeichen enthaöten.<br/>',
  'the group new users automatically belong to' => 'Die Standardgruppe für einen neuen Benutzer',
  'userGroups version' => 'Version von userGroups',
  'users can set their own home' => 'Benutzer können ihre Startseite wählen',
  'users with just admin write permissions won\'t see the Main Configuration and Cron Jobs panels' => 'Benutzer mit Adminrechten können weder die Hauptkonfiguration noch die Cronjob-Seiten sehen',
  'users with userGroups admin admin permission will have access to everything, just like root' => 'Benutzer mit Adminrechten habe Zugriff zu allem, wie der Root-Benutzer',
);
