<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'can change permission of user and groups whose group level is below his own.' => 'Kann Zugriffsrechte von Benutzern und Gruppen änderen, deren Level niedriger als der eigene sind.',
  'can create users and groups and has all the permission of a user with user admin permissions. The level rule still apply.' => 'Kann Benutzer und Gruppen anlegen und hat Berechtigungen wie ein Administrator. Die Level-Regel werden eingehalten.',
  'can edit other users, ban them and approve their registrations.' => 'Kann andere Benutzer bearbeiten, bannen oder Registrierung genemigen.',
  'can invite other users.' => 'Kann andere Benutzer einladen',
  0 => '',
  'view documentation.' => 'Dokumentation anzeigen',
);
