<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'you didn\'t initialize the UGCron singleton' => 'Das UGCron Singleton wurde nicht initialisiert.',
  'Cronjob not installed' => 'Der Cron Job wurde nicht installiert',
  'No description found for the requested cron job' => 'Es konnte keine Beschreibung für den gewünschten Cron Job gefunden werden.',
  'You didn\'t set the cron table name' => 'Sie haben keinen Namen für die Cron Job Tabelle angegeben.',
  'You have to provide a name for the cronjob' => 'Sie müssen einen Namen für die Cron Job Tabelle angeben.',
  'could not install the module. Lapse must be an integer' => 'Das Modul konnte nicht installiert werden. Der Wert für die Zeitspanne muss ein ganzzahliger Wert sein.',
  'delete users who have not been activated for more then 7 days' => 'Löscht Benutzerkonten die seit mehr als 7 Tagen nicht aktiviert wurden.',
  'installed and running' => 'Installiert und Funktionsfähig',
  'not installed' => 'Nicht installiert',
  'reactivate users whose ban period is over' => 'Reaktiviert Benutzer deren Bann-Periode vorbei ist.',
  'the model provided is not an instance of CActiveRecord' => 'Das angegeben Model ist keine Instanz von CActiveRecord.',
  'the provided criteria are not an instance of CDbCriteria' => 'Das angegebene Kriterium ist keine Instanz von CDbCriteria.',
  'you didn\'t provide a valid action' => 'Sie haben keine gültige Aktion angegeben.',
  'you didn\'t set the columns to update' => 'Sie haben keine Spalte zum Berabeiten angegeben.',
);
