<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'A password change has been requested.<br/>You won\'t be able to login until you change the password.' => '&Egrave; stato richiesto un cambio di password.<br/>Non potrai loggare finch&egrave; non avrai cambiato la tua password.',
  'Access' => 'Zugriff',
  'Account not active' => 'Benutzerkonto nicht aktiv',
  'Activate the account' => 'Benutzeraccount aktivieren',
  'An Error Occurred. Please try later.' => 'Es ist ein Fehler aufgetreten. Bitte versuchen Sie es zu einem späteren Zeitpunkt.',
  'An email containing the instructions to reset your password has been sent to your email address: {email}' => 'Es wurde eine E-mail mit Anweisungen zum Zurücksetzung des Passworts and die Adresse: {email} verschickt.',
  'An email was sent with the instructions to activate your account to the address {email}.' => 'Es wurde eine E-mail mit einer Anleitung zum Aktivierem Ihres Accounts an folgende Adresse: {email} verschickt.',
  'An invitation email was sent to the address {email}' => 'Es wurde eine Einladungs-E-mail an die Adresse: {email} verschickt.',
  'Approve Registration' => 'Registrierung überprüfen',
  'Ban User' => 'Benutzer bannen',
  'Change Password' => 'Passwort ändern',
  'Confirm Password' => 'Passwort bestätigen',
  'Creation Date' => 'Erzeugungsdatum',
  'Data Updated Successfully' => 'Die Daten wurden bearbeitet.',
  'Delete' => 'Löschen',
  'Documentation' => 'Dokumentation',
  'Edit Profile' => 'Profil bearbeiten',
  'Edit {username}\'s Profile' => 'Profil von {username} bearbeiten',
  'Email' => 'E-mail',
  'Fields with {*} are required.' => 'Benötigte Felder sind mit einem {*} markiert.',
  'General Info' => 'Allgemeine Informationen',
  'Group' => 'Gruppe',
  'Group Level' => 'Gruppenlevel',
  'Group Name' => 'Gruppenname',
  'Groups' => 'Gruppen',
  'Home' => 'Startseite',
  'Impossible to send email to the address {email}' => 'An die Adresse {email} konnte keine E-mail verschickt werden.',
  'Invalid email address' => 'Ungültige E-mail-Adresse',
  'Invite User' => 'Benutzer Einladen',
  'Level' => 'Level',
  'Login' => 'Einloggen',
  'Login Required' => 'Einloggen erforderlich',
  'My Profile' => 'Mein Profil',
  'Name' => 'Name',
  'Old Password' => 'Altes Passwort',
  'Password' => 'Passwort',
  'Password Reset: Answer' => 'Passwort Zurücksetzen: Antwort',
  'Password Reset: Question' => 'Passwort Zurücksetzen: Frage',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => 'Bitte geben Sie die Zeichen aus dem obigen Bild ein.',
  'Please fill out the following form with your login credentials:' => 'Bitte füllen Sie das folgende Formular mit Ihren Anmeldedaten aus:',
  'Proceed' => 'Weiter',
  'Recovery Mode' => 'Wiederhertellungsmodus',
  'Register' => 'Registrierung',
  'Registration Complete, you can now login.' => 'Die Registrierung is abgeschlossen, Sie können sich jetzt einloggen.',
  'Registration Complete. You now have to wait for an admin to approve your account.' => 'Die Registrierung is abgeschlossen. Sie müssen nun abwarten, bis ein Administrator Ihren Benutzerkonto aktiviert hat.',
  'Remember Me' => 'Erinnere Dich an mich',
  'Request New Password' => 'Neues Passwort anfordern',
  'Resend Email' => 'E-mail erneut senden',
  'Root Tools' => 'Root-Werkzeuge',
  'Root password must contain at least 2 digits and 2 letters and have at least 5 characters' => 'Das Root-Passwort muss mindestens 2 Ziffern und 2 Buchstaben enthalten und muss mindestens aus 5 Zeichen bestehen.',
  'Save' => 'Speichern',
  'Security' => 'Sicherheit',
  'The activation email was successfully sent to {email}' => 'Die Aktivierungs-E-mail wurde erfolgreich an die Adresse {email} verschickt.',
  'The requested page does not exist.' => 'Die angeforderte Seite existiert nicht.',
  'This account is not approved yet' => 'Dieser Account wurde bisher noch nicht freigeschaltet',
  'Update' => 'Bearbeiten',
  'Update External Profile' => 'Externes Profil bearbeiten',
  'Update User' => 'Benutzer bearbeiten',
  'Update User Profile' => 'Profildaten ändern',
  'User Invitation' => 'Benutzer einladen',
  'User List' => 'Benutzerliste',
  'User Name' => 'Benutzernamen',
  'User Registration' => 'Benutzerregistration',
  'Username' => 'Benutzernamen',
  'Users' => 'Benutzer',
  'Verification Code' => 'Verifizierungskode',
  'We are sorry, but your account is banned' => 'Es tut uns leid, aber ihr Benutzerkonto wurde gebannt.',
  'You are not allowed to update other accounts' => 'Sie haben keine Berechtigung um andere Benutzerkonten zu bearbeieten.',
  'You didn\'t enter the correct password' => 'Das eingetippte Passwort is nicht korrekt.',
  'You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.' => '',
  'profile' => 'Profil',
  'register' => 'Registrieren',
  'the confirmation password doesn\'t match the password' => 'Das Bestätigungspasswort is nicht mit dem Passwotrt identisch.',
  'the password must be of at least 5 characters' => 'Das Passwort muss mindestens 5 zeichen enthalten.',
  'the password must contain at least 2 digits and 2 letters and have at least 5 characters' => 'Das Passwort muss mindestens 2 Ziffern und 2 Buchstaben enthalten und muss mindestens aus 5 Zeichen bestehen.',
  'the password must contain at least 2 digits, 2 letters and a special character' => 'Das Root-Passwort muss mindestens 2 Ziffern und 2 Buchstaben und einem speziellen Zeichen bestehen.',
  'username must be at least 4 characters and can only be alphanumeric' => 'Der Benutzername muss mindestens aus 4 alphanumerischen Zeichen bestehen.',
  '{username}\'s Profile' => 'Profile von {username}',
);
