<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Unable to create the tables in the database. Make sure that your db user has the necessary permissions to create a new table.<br/>This release only officially supports Mysql and PostgreSQL.' => 'Die Tabellen können in der Datenbank nicht erstellt werden. Stellen Sie sicher, dass Ihr Benutzerkonto die notwendigen Berechtigungen hat, um eine neue Tabelle zu erstellen.<br/>Diese Version unterstützt offiziell nur MySQL und PostgreSQL.',
  'You didn\'t correctly set the class property in the user component.<br/>Value set: <b>{class}</b><br/>Value expected: <b>WebUserGroups</b>' => 'Das attribute Klasse hat in der Benutzerkomponente eine falschen Wert.<br/>Aktueller Wert: <b> {class}</b><br/>Erwarteter Wert: <b>WebUserGroups</b>',
  'You didn\'t set an adminEmail param inside your application configuration file.' => 'Sie haben keine Administrator E-mail in der Konfigurationsdatei der Applikation angegeben.',
  'You didn\'t set the access code in your config file.' => 'Sie haben einen Zugangscode in der Konfigurationsdatei gesetzt.',
  '<p>userGroups Installed! To continue the configuration please login</p><p>The new Controller class file has been created. Your old controller has been saved in the component folder with the name <i>_old_Controller.php</i></p>' => 
  '<p>userGroups Installiert! Loggen Sie sich ein um mit der Konfigurations fortzufahren</p><p>Die neue Controller-Klassen-Datei wurdeerstellt. Ihre alter Controller wurde im component-Ordner unter dem Namen <i>_old_Controller.php</i></p> gespeichert.',
  'Access Code' => 'Zugriffskode',
  'Error during installation. Couldn\'t create root group with id {id}' => 'Installationsfehler. Es konnte keine Root-Gruppe mit der ID {id} angelegt werden.',
  'Error during installation. Couldn\'t create root user with id {id}' => 'Installationsfehler. Es konnte kein Root-Benutzer mit der ID {id} angelegt werden.',
  'Password Reset: Question' => 'Passwort Zurücksetzen: Frage',
  'Retype Root Password' => 'Root-Passwort wiederholen',
  'Root Email' => 'Root-Email',
  'Root Password' => 'Root-Passwort',
  'Root User' => 'Root-Benutzer',
  'Setting not installed. Installation abort.' => 'Einstellungen nihct installiert. Installation abgebrochen.',
  'The two access codes don\'t match.' => 'Die zwei Zugriffskodes sind sind nicht identisch',
  'Unable to write the file {path}.' => 'Die Datei {path} kann nicht geschrieben werden-',
  'for security reasons the root password must contain at least 2 digits and 2 letters' => 'Aus Gründen der Sicherheit muss das Root-Passwort mindestens zwei Buchstaben und zwei Zahlen enthalten.',
  'the Access Code cannot be blank' => 'Der Zugriffskode kann nicht leer sein',
  'the confirmation password doesn\'t match the password' => 'Das Bestätigungspasswort stimmt nicht mit dem Passwort überein',
);
