<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'About' => 'Über',
  'Admin' => 'Admin',
  'Advanced Search' => 'Erweiterte Suche',
  'All Rights Reserved.' => 'Alle Rechte vorbehalten.',
  'Are you sure you want to delete this item?' => 'Sind sie sicher, dass Sie dieses Element löschen wollen?',
  'Attribute|Attributes' => 'Attribut|Attribute',
  'Base Unit Factor' => 'Faktor für Basiseinheit',
  'Categorie|Categories' => 'Kategorie|Kategorien',
  'Contact' => 'Kontakt',
  'Contact Us' => 'Schicken Sie uns eine E-mail',
  'Course|Courses' => 'Gang|Gänge',
  'Create' => 'Erzeuge',
  'Delete' => 'Lösche',
  'Description' => 'Beschreibung',
  'E-mail' => 'E-mail',
  'Error' => 'Fehler',
  'Fields with {asterisk} are required.' => 'Benötigte Felder sind mit einem {asterisk} markiert.',
  'Home' => 'Startseite',
  'ID' => 'ID',
  'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Wenn Sie Fragen zum Kochbuch haben können Sie das Formular benutzen, um mit uns in Kontakt zu treten. Vielen Dank!',
  'Incorrect username or password.' => 'Falscher Benutzername oder Paßwort.',
  'Ingredient' => 'Zutat',
  'Ingredient Section' => 'Zutatenabschnitt',
  'Ingredient Section Recipe' => 'Zutatenabschnitt Rezepte',
  'Ingredients list cannot be blank.' => 'Die Zutatenliste darf nicht leer sein.',
  'Ingredient|Ingredients' => 'Zutat|Zutaten',
  'Is Base Unit' => 'Ist Basiseinheit',
  'List' => 'Zeige',
  'Login' => 'Einloggen',
  'Logout' => 'Ausloggen',
  'Manage' => 'Verwalte',
  'Message body' => 'Nachricht',
  'Name' => 'Name',
  'Name of Step' => 'Name des Schritts',
  'Operations' => 'Operationen',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => 'Bitte geben Sie die Zeichen aus dem obigen Bild ein. Groß/Kleinschreibung wird nicht unterschieden.',
  'Quantity' => 'Quantität',
  'Quantity or Number of Portions' => 'Guantität oder Anzahl der Portionen',
  'Recipe' => 'Rezept',
  'Recipe Name' => 'Rezept Name',
  'Recipe|Recipes' => 'Rezept|Rezepte',
  'Remember me next time' => 'Erinnere dich an mich',
  'Seq No' => 'Sequenznummer',
  'Short Desc' => 'Kurzbeschreibung',
  'Subject' => 'Betreff',
  'The requested page does not exist.' => 'Die gewünschte Seite existiert nicht',
  'Unit' => 'Einheit',
  'Unit Type' => 'Einheitentype',
  'Unit Type|Unit Types' => 'Einheitentyp|Einheitentypen',
  'Unit usage' => 'Verwendung der Einheiten',
  'Unit|Units' => 'Einheit|Einheiten',
  'Update' => 'Ändere',
  'Verification Code' => 'Überprüfungskode',
  'View' => 'Zeige',
  'You may optionally enter a compariso operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.' => 'Sie können optional einen Vergleichsoperator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> oder <b>=</b>) vor jedem Suchkriterium angeben um die Suche einzuschränken.',
);
